name: Publish
on:
  workflow_dispatch

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: microsoft/setup-powershell@v1

      - name: Publish
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: |
          pwsh -File Publish.ps1
